// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD818Vns8_w9BsLWySFcTBKHK1c5Qsk6Cs',
    appId: '1:8544868500:web:5f896e5acc44d36d153c81',
    messagingSenderId: '8544868500',
    projectId: 'flutter-market-4408f',
    authDomain: 'flutter-market-4408f.firebaseapp.com',
    storageBucket: 'flutter-market-4408f.appspot.com',
    measurementId: 'G-Q0PJ7XXV8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6waaH5FMSMLsImySkh5FqVTprwDhfXdA',
    appId: '1:8544868500:android:81447630b5c9fcbd153c81',
    messagingSenderId: '8544868500',
    projectId: 'flutter-market-4408f',
    storageBucket: 'flutter-market-4408f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9GNP8JCxgoAyQUk5wzHyF2qr_zeXpOm4',
    appId: '1:8544868500:ios:cabc2081fe61b885153c81',
    messagingSenderId: '8544868500',
    projectId: 'flutter-market-4408f',
    storageBucket: 'flutter-market-4408f.appspot.com',
    iosClientId: '8544868500-17j32nt03f986u1h3aj12qdm09mi635u.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.flutterMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9GNP8JCxgoAyQUk5wzHyF2qr_zeXpOm4',
    appId: '1:8544868500:ios:cabc2081fe61b885153c81',
    messagingSenderId: '8544868500',
    projectId: 'flutter-market-4408f',
    storageBucket: 'flutter-market-4408f.appspot.com',
    iosClientId: '8544868500-17j32nt03f986u1h3aj12qdm09mi635u.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.flutterMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD818Vns8_w9BsLWySFcTBKHK1c5Qsk6Cs',
    appId: '1:8544868500:web:334bc0d2686c3af8153c81',
    messagingSenderId: '8544868500',
    projectId: 'flutter-market-4408f',
    authDomain: 'flutter-market-4408f.firebaseapp.com',
    storageBucket: 'flutter-market-4408f.appspot.com',
    measurementId: 'G-F504JCMHZH',
  );
}
